import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { DelegationService } from '../services/delegation-service.js';
import type { TaskPriority } from '@veritas-kanban/shared';

describe('DelegationService', () => {
  const originalCwd = process.cwd();
  let tempDir: string;
  let service: DelegationService;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'vk-delegation-'));
    process.chdir(tempDir);
    process.env.DATA_DIR = tempDir;
    service = new DelegationService();
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    delete process.env.DATA_DIR;
    await rm(tempDir, { recursive: true, force: true });
  });

  beforeEach(async () => {
    // Isolate tests by removing files generated by previous tests
    const fs = await import('fs/promises');
    const path = await import('path');
    const dir = path.join(tempDir, '.veritas-kanban');
    await fs.mkdir(dir, { recursive: true });
    await fs.unlink(path.join(dir, 'delegation.json')).catch(() => {});
    await fs.unlink(path.join(dir, 'delegation-log.json')).catch(() => {});

    // We must reset the module-level singletons, NOT just create a new instance!
    // DelegationService itself doesn't export the class as a singleton, but it
    // caches state via `this.settingsLoaded`. Wait! The issue is that the imported
    // `DelegationService` class points to the SAME instance if it's imported via
    // `getDelegationService()`. Actually, we are using `new DelegationService()`.
    // Why is state leaking? Because `DELEGATION_DIR` inside `delegation-service.ts`
    // is set AT MODULE LOAD TIME based on `process.cwd()`.
    // `const PROJECT_ROOT = path.resolve(process.cwd(), '..');`
    // Wait... `process.cwd()` AT MODULE LOAD is whatever Vitest runs as!
    // So all instances write to the SAME `.veritas-kanban` directory in `server/..`!
    // This is a common test isolation bug.
    // To fix this, we need to mock the paths or use `vi.resetModules()` BEFORE importing.
    const { vi } = await import('vitest');
    vi.resetModules();

    // Override process.cwd() BEFORE importing delegation-service
    // so `PROJECT_ROOT` resolves to `tempDir`.
    // `PROJECT_ROOT` is `path.resolve(process.cwd(), '..')`
    // So we need process.cwd() to return a path inside tempDir.
    // Let's create a dummy folder inside tempDir and chdir into it.
    const runDir = path.join(tempDir, 'dummy-cwd');
    await fs.mkdir(runDir, { recursive: true });
    process.chdir(runDir);

    const { DelegationService: FreshService } = await import('../services/delegation-service.js');
    service = new FreshService();
  });

  const validDelegation = {
    delegateAgent: 'agent-1',
    expires: new Date(Date.now() + 1000 * 60 * 60).toISOString(), // 1 hour from now
    scope: { type: 'all' as const },
    createdBy: 'user-1'
  };

  it('sets and gets delegation', async () => {
    await service.setDelegation(validDelegation);

    const settings = await service.getDelegation();
    expect(settings).not.toBeNull();
    expect(settings?.delegateAgent).toBe(validDelegation.delegateAgent);
    expect(settings?.enabled).toBe(true);
    expect(settings?.scope).toEqual(validDelegation.scope);
  });

  it('returns null when no delegation is set', async () => {
    const settings = await service.getDelegation();
    expect(settings).toBeNull();
  });

  it('auto-disables expired delegation', async () => {
    await service.setDelegation({
      ...validDelegation,
      expires: new Date(Date.now() - 1000).toISOString() // 1 second ago
    });

    const settings = await service.getDelegation();
    expect(settings?.enabled).toBe(false);
  });

  it('revokes delegation', async () => {
    await service.setDelegation(validDelegation);

    const revoked = await service.revokeDelegation();
    expect(revoked).toBe(true);

    const settings = await service.getDelegation();
    expect(settings?.enabled).toBe(false);
  });

  describe('canApprove', () => {
    it('allows approval when agent and scope match', async () => {
      await service.setDelegation(validDelegation);

      const result = await service.canApprove('agent-1', { id: 'task-1' });
      expect(result.allowed).toBe(true);
    });

    it('denies approval when agent does not match', async () => {
      await service.setDelegation(validDelegation);

      const result = await service.canApprove('agent-2', { id: 'task-1' });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBe('Agent is not the delegate');
    });

    it('denies approval when delegation is expired', async () => {
      await service.setDelegation({
        ...validDelegation,
        expires: new Date(Date.now() - 1000).toISOString()
      });

      const result = await service.canApprove('agent-1', { id: 'task-1' });
      expect(result.allowed).toBe(false);
      // Since it auto-disables expired delegations, it will say "No active delegation"
      // or "Delegation has expired" depending on the internal order.
      // Wait, `setDelegation` sets it with `enabled: true` and current `expires`.
      // `canApprove` calls `loadSettings()`. Since `settingsLoaded` is true, it checks expiry and sets `enabled` to false.
      // Then `canApprove` checks `!delegation.enabled` and returns "No active delegation".
      expect(result.reason).toBe('No active delegation');
    });

    it('denies approval based on priority exclusions', async () => {
      await service.setDelegation({
        ...validDelegation,
        excludePriorities: ['highest' as TaskPriority]
      });

      const result = await service.canApprove('agent-1', { id: 'task-1', priority: 'highest' as TaskPriority });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBe('Priority "highest" is excluded from delegation');
    });

    it('denies approval based on tag exclusions', async () => {
      await service.setDelegation({
        ...validDelegation,
        excludeTags: ['skip-delegation']
      });

      const result = await service.canApprove('agent-1', { id: 'task-1', tags: ['bug', 'skip-delegation'] });
      expect(result.allowed).toBe(false);
      expect(result.reason).toBe('Task has excluded tag: skip-delegation');
    });

    it('denies approval for project scope mismatch', async () => {
      await service.setDelegation({
        ...validDelegation,
        scope: { type: 'project', projectIds: ['project-1'] }
      });

      const result1 = await service.canApprove('agent-1', { id: 'task-1', project: 'project-2' });
      expect(result1.allowed).toBe(false);
      expect(result1.reason).toBe('Project "project-2" not in delegation scope');

      const result2 = await service.canApprove('agent-1', { id: 'task-2', project: 'project-1' });
      expect(result2.allowed).toBe(true);
    });

    it('denies approval for priority scope mismatch', async () => {
      await service.setDelegation({
        ...validDelegation,
        scope: { type: 'priority', priorities: ['low' as TaskPriority] }
      });

      const result1 = await service.canApprove('agent-1', { id: 'task-1', priority: 'high' as TaskPriority });
      expect(result1.allowed).toBe(false);
      expect(result1.reason).toBe('Priority "high" not in delegation scope');

      const result2 = await service.canApprove('agent-1', { id: 'task-2', priority: 'low' as TaskPriority });
      expect(result2.allowed).toBe(true);
    });
  });

  describe('logging', () => {
    beforeEach(async () => {
      // Isolate logging tests by removing logging files
      const fs = await import('fs/promises');
      const path = await import('path');
      const dir = path.join(tempDir, '.veritas-kanban');
      await fs.unlink(path.join(dir, 'delegation-log.json')).catch(() => {});

      // Force clear internal caches of the class
      (service as any).log = { approvals: [] };
      (service as any).logLoaded = false;
    });

    it('logs approval and retrieves it', async () => {
      await service.setDelegation(validDelegation);

      const approval = await service.logApproval({
        taskId: 'task-1',
        taskTitle: 'Test Task',
        agent: 'agent-1'
      });

      expect(approval.taskId).toBe('task-1');
      expect(approval.agent).toBe('agent-1');

      const logs = await service.getApprovalLog();
      expect(logs).toHaveLength(1);
      expect(logs[0].taskId).toBe('task-1');
    });

    it('filters approval logs by taskId and agent', async () => {
      await service.setDelegation(validDelegation);

      await service.logApproval({ taskId: 'task-1', taskTitle: 'Task 1', agent: 'agent-1' });
      await service.logApproval({ taskId: 'task-2', taskTitle: 'Task 2', agent: 'agent-2' });

      const logsTask1 = await service.getApprovalLog({ taskId: 'task-1' });
      expect(logsTask1).toHaveLength(1);
      expect(logsTask1[0].taskId).toBe('task-1');

      const logsAgent2 = await service.getApprovalLog({ agent: 'agent-2' });
      expect(logsAgent2).toHaveLength(1);
      expect(logsAgent2[0].agent).toBe('agent-2');
    });

    it('limits returned approval logs', async () => {
      await service.setDelegation(validDelegation);

      await service.logApproval({ taskId: 'task-1', taskTitle: 'Task 1', agent: 'agent-1' });
      await service.logApproval({ taskId: 'task-2', taskTitle: 'Task 2', agent: 'agent-1' });
      await service.logApproval({ taskId: 'task-3', taskTitle: 'Task 3', agent: 'agent-1' });

      const logs = await service.getApprovalLog({ limit: 2 });
      expect(logs).toHaveLength(2);
    });
  });
});
